# Site Settings
title: Handlebar Labs | Your Digital Partner
baseurl: "/"

# Build settings
markdown: kramdown
# gems: ['jekyll-less']
exclude: ['dploy.yaml', 'Gruntfile.js', 'package.json', 'README.md']
